data_paths:
  Crema: kaggle/Crema/
  Ravdess: kaggle/Ravdess/audio_speech_actors_01-24/
  Savee: kaggle/Savee/
  Tess: kaggle/Tess/

# choose database
df_path: data/tess_df.csv
#  Crema: data/crema_df.csv
#  Ravdess: data/ravdess_df.csv
#  Savee: data/savee_df.csv
#  Tess: data/tess_df.csv


model_path: Models/best_weights_tess.hdf5
#  Crema: Models/best_weights_crema.hdf5
#  Ravdess: Models/best_weights_ravdess.hdf5
#  Savee: Models/best_weights_savee.hdf5
#  Tess: Models/best_weights_tess.hdf5


#train_config:
batch_size: 128
epochs: 160
validation_split: 0.2

#data_augmentation:
noise_rate: 0.018
stretch_rate: 0.6
pitch_factor: 2
